version: 0.2

batch:
  build-list:
    - identifier: build1
      env:
        variables:
          GOOS: darwin
          GOARCH: amd64
    - identifier: build2
      env:
        variables:
          GOOS: darwin
          GOARCH: arm64
    - identifier: build3
      env:
        variables:
          GOOS: windows
          GOARCH: amd64
    - identifier: build4
      env:
        variables:
          GOOS: windows
          GOARCH: arm
    - identifier: build5
      env:
        variables:
          GOOS: linux
          GOARCH: amd64
    - identifier: build6
      env:
        variables:
          GOOS: linux
          GOARCH: arm64

phases:
  install:
    commands:
      - goenv install 1.16.3 -s
      - goenv local 1.16.3

  build:
    commands:
      - mv listObjects.go listObjects.go.tmp
      - cat listObjects.go.tmp | envsubst | tee listObjects.go
      - go build listObjects.go

artifacts:
  files:
    - 'listObjects'
    - 'listObjects.exe'
    - 'README.md'
  name: listObjects_${GOOS}_${GOARCH}_$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7).zip
